from __future__ import annotations

from pathlib import Path
import uuid

from rdkit import Chem
from rdkit.Geometry import Point3D

import pytest

from src.quantum.mopac_adapter import MopacError, MopacOptimizer


TEST_TEMP_DIR = Path(__file__).resolve().parent / ".tmp"


def _molecule_with_conformer(smiles: str) -> Chem.Mol:
    base_molecule = Chem.MolFromSmiles(smiles)
    assert base_molecule is not None
    molecule = Chem.AddHs(base_molecule)
    conformer = Chem.Conformer(molecule.GetNumAtoms())
    for atom_index in range(molecule.GetNumAtoms()):
        conformer.SetAtomPosition(atom_index, Point3D(float(atom_index), 0.0, 0.0))
    molecule.AddConformer(conformer)
    return molecule


def test_build_keywords_includes_charge_and_eps() -> None:
    optimizer = MopacOptimizer({"method": "PM7", "use_mmok": True, "use_eps": True, "eps": 78.39})

    assert optimizer._build_keywords(1) == "PM7 MMOK OPT XYZ CHARGE=1 EPS=78.39"


def test_build_keywords_omits_eps_when_disabled() -> None:
    optimizer = MopacOptimizer({"method": "PM7", "use_mmok": True, "use_eps": False})

    assert optimizer._build_keywords(-1) == "PM7 MMOK OPT XYZ CHARGE=-1"


def test_build_keywords_uses_selected_mopac_method() -> None:
    optimizer = MopacOptimizer({"method": "pm6-d3h4x", "use_mmok": True, "use_eps": False})

    assert optimizer._build_keywords(0) == "PM6-D3H4X MMOK OPT XYZ CHARGE=0"


def test_build_keywords_defaults_to_pm7_when_method_is_blank() -> None:
    optimizer = MopacOptimizer({"method": "   ", "use_mmok": True, "use_eps": False})

    assert optimizer._build_keywords(0) == "PM7 MMOK OPT XYZ CHARGE=0"


def test_net_charge_uses_final_formal_charge() -> None:
    optimizer = MopacOptimizer({})
    molecule = _molecule_with_conformer("C[NH3+]")

    assert optimizer._net_charge(molecule) == 1


def test_serialized_charge_from_molblock_reads_explicit_charge_lines() -> None:
    optimizer = MopacOptimizer({})
    molecule = _molecule_with_conformer("C[NH3+]")

    assert optimizer._serialized_charge_from_molblock(molecule) == 1


def test_reconcile_charge_prefers_formal_charge_when_serialized_charge_differs(monkeypatch) -> None:
    optimizer = MopacOptimizer({})
    molecule = _molecule_with_conformer("C[NH3+]")

    monkeypatch.setattr(MopacOptimizer, "_serialized_charge_from_molblock", lambda self, mol: 0)

    charge, source, note = optimizer._reconcile_charge(molecule)

    assert charge == 1
    assert source == "formal_charge_preferred"
    assert note == "formal_charge=1; molblock_charge=0"


def test_parse_final_geometry_from_arc() -> None:
    optimizer = MopacOptimizer({})
    arc_text = """
                     SUMMARY OF  PM7 CALCULATION

          HEAT OF FORMATION       =        -65.21096 KCAL/MOL =    -272.84268 KJ/MOL

          FINAL GEOMETRY OBTAINED
 PM7 MMOK OPT XYZ CHARGE=0 EPS=78.39
 Water test
 Generated by probe
  O    -0.00393124 +1  -0.00478314 +1   0.00000000 +0
  H     0.96170357 +1   0.00133787 +1   0.00000000 +0
  H    -0.23897233 +1   0.93054527 +1   0.00000000 +0
 
"""

    geometry = optimizer._parse_final_geometry(arc_text)
    heat = optimizer._parse_heat_of_formation(arc_text)

    assert geometry == [
        ("O", -0.00393124, -0.00478314, 0.0),
        ("H", 0.96170357, 0.00133787, 0.0),
        ("H", -0.23897233, 0.93054527, 0.0),
    ]
    assert heat == -65.21096


def test_optimize_raises_clear_error_when_mopac_binary_is_missing(monkeypatch) -> None:
    access_code = "WATER_MISSING_BINARY"
    optimizer = MopacOptimizer(
        {
            "method": "PM7",
            "use_mmok": True,
            "use_eps": True,
            "eps": 78.39,
            "binary_path": str(TEST_TEMP_DIR / "missing_mopac.exe"),
            "temp_dir": str(TEST_TEMP_DIR),
        }
    )

    monkeypatch.setattr(MopacOptimizer, "_create_temp_dir", lambda self: TEST_TEMP_DIR)
    monkeypatch.setattr("src.quantum.mopac_adapter.shutil.rmtree", lambda *args, **kwargs: None)
    monkeypatch.setattr(
        "src.quantum.mopac_adapter.subprocess.run",
        lambda *args, **kwargs: (_ for _ in ()).throw(FileNotFoundError("missing")),
    )

    with pytest.raises(MopacError, match="MOPAC executable not found"):
        optimizer.optimize(_molecule_with_conformer("O"), access_code)


def test_optimize_can_preserve_generated_mopac_files(monkeypatch) -> None:
    access_code = "WATER_PRESERVE"
    job_stem = "mopac_test_job"
    test_root = TEST_TEMP_DIR / f"preserve_{uuid.uuid4().hex}"
    job_dir = test_root / "job_dir"
    preserved_dir = test_root / "preserved_dir"
    optimizer = MopacOptimizer(
        {
            "method": "PM7",
            "use_mmok": True,
            "use_eps": True,
            "eps": 78.39,
            "binary_path": str(TEST_TEMP_DIR / "fake_mopac.exe"),
            "temp_dir": str(TEST_TEMP_DIR),
            "preserve_files": True,
            "preserved_files_dir": str(preserved_dir),
        }
    )

    job_dir.mkdir(parents=True, exist_ok=True)
    preserved_dir.mkdir(parents=True, exist_ok=True)
    monkeypatch.setattr(MopacOptimizer, "_create_temp_dir", lambda self: job_dir)
    monkeypatch.setattr(MopacOptimizer, "_job_stem", lambda self: job_stem)
    monkeypatch.setattr("src.quantum.mopac_adapter.shutil.rmtree", lambda *args, **kwargs: None)

    def fake_run(*args, **kwargs):
        (job_dir / f"{job_stem}.arc").write_text(
            """
                     SUMMARY OF  PM7 CALCULATION

          HEAT OF FORMATION       =        -65.21096 KCAL/MOL =    -272.84268 KJ/MOL

          FINAL GEOMETRY OBTAINED
 PM7 MMOK OPT XYZ CHARGE=0 EPS=78.39
 Water test
 Generated by probe
  O    -0.00393124 +1  -0.00478314 +1   0.00000000 +0
  H     0.96170357 +1   0.00133787 +1   0.00000000 +0
  H    -0.23897233 +1   0.93054527 +1   0.00000000 +0
 
""",
            encoding="utf-8",
        )
        (job_dir / f"{job_stem}.out").write_text("done", encoding="utf-8")
        (job_dir / f"{job_stem}.end").write_text("done", encoding="utf-8")

        class Result:
            returncode = 0
            stderr = ""
            stdout = "ok"

        return Result()

    monkeypatch.setattr("src.quantum.mopac_adapter.subprocess.run", fake_run)

    result = optimizer.optimize(_molecule_with_conformer("O"), access_code)

    assert len(result.preserved_files) == 4
    assert all(Path(path).exists() for path in result.preserved_files)
    assert (preserved_dir / access_code / f"{job_stem}.mop").exists()
    assert (preserved_dir / access_code / f"{job_stem}.arc").exists()
